version: "3.0"

services:
  sei:
    build:
      context: .
      args:
        - REL_TAG=$REL_TAG
    volumes:
      - ./sei:/root/.sei
      - ./scripts:/scripts
    restart: unless-stopped
    env_file: .env
    logging:
      options:
        max-size: "1g"
