version: "3.0"

services:
    sei:
        build: .
        volumes:
            - ./sei:/root/.sei
            - ./config:/root/sei-configs
        ports:
            - 80:26657
        env_file: .env
        restart: on-failure
