services:
  master: &build
    platform: linux/x86_64
    build:
      context: .
      args:
        - REL_TAG=$REL_TAG
        - COSMOVISOR_TAG=$COSMOVISOR_TAG
        - UPGRADE_TAG=$UPGRADE_TAG
    env_file: .env
    image: senseinode/sei:latest

  sei:
    <<: *build
    container_name: sei-network
    image: senseinode/sei:latest
    volumes:
      - ./sei:/root/.sei
      - ./scripts:/scripts
      - UPGRADE_TAG=$UPGRADE_TAG
    ports:
      - 26656:26656
    restart: unless-stopped
    env_file: .env
    logging:
      options:
        max-size: "1g"

  oracles:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile.oracle
      args:
        - REL_TAG=$REL_TAG
        - COSMOVISOR_TAG=$COSMOVISOR_TAG
        - UPGRADE_TAG=$UPGRADE_TAG
    volumes:
      - ./sei-oracle:/root/.sei
      - ./scripts:/scripts
      - ./oracles-config.toml:/root/oracles-config.toml
    ports:
      - 127.0.0.1:7171:7171
    restart: on-failure
    env_file: .env
    entrypoint: ["sh", "/scripts/start-oracle.sh"]
    logging:
      options:
        max-size: "1g"
