version: "3.0"

services:
  sei:
    build:
      context: .
      args:
        - REL_TAG=$REL_TAG
    volumes:
      - ./sei:/root/.sei
      - ./scripts:/scripts
    ports:
      - 26656:26656
      - 16857:16857
    restart: unless-stopped
    env_file: .env
    logging:
      options:
        max-size: "1g"
