services:
  sei:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REL_TAG=$REL_TAG
        - COSMOVISOR_TAG=$COSMOVISOR_TAG
        - UPGRADE_TAG=$UPGRADE_TAG
    volumes:
      - ./sei:/root/.sei
      - ./scripts:/scripts
    ports:
      - 26656:26656
    restart: unless-stopped
    env_file: .env
    logging:
      options:
        max-size: "1g"

  oracles:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile.oracle
      args:
        - REL_TAG=$REL_TAG
        - COSMOVISOR_TAG=$COSMOVISOR_TAG
        - UPGRADE_TAG=$UPGRADE_TAG
    volumes:
      - ./sei-oracle:/root/.sei
      - ./scripts:/scripts
      - ./oracles-config.toml:/root/oracles-config.toml
    ports:
      - 127.0.0.1:7171:7171
    restart: on-failure
    env_file: .env
    entrypoint: ["sh", "/scripts/start-oracle.sh"]
    logging:
      options:
        max-size: "1g"
