version: "3.0"

services:
    sei:
        build: .
        volumes:
            - ./sei:/root/.sei
        ports:
            - 26656:26656
            - 80:26657
        env_file: .env
        restart: on-failure
